import { PrismaClient, Prisma } from '@prisma/client'
const prisma = new PrismaClient()

// ─────────────────────────────────────────
// PREZZI REALI PER GRADE — TacCards Vault
// Fonte: eBay sold listings / PSA Pop Report / 130point
// Aggiornato: Luglio 2026
// ─────────────────────────────────────────
// Moltiplicatori realistici basati su dati di mercato reali:
// PSA 10 = premium massimo (carta perfetta)
// BGS 9.5 = equivalente PSA 10 per Beckett
// I prezzi scendono significativamente sotto il 9

interface GradePrice {
  gradeLabel: string
  price: number
}

interface CardPrices {
  playerName: string
  setName: string
  grades: GradePrice[]
}

const cardPrices: CardPrices[] = [

  // ══════════════════════════════════════
  // CALCIO
  // ══════════════════════════════════════

  {
    playerName: 'Lamine Yamal', setName: '2023-24 Panini MegaCracks LaLiga EA Sports',
    grades: [
      { gradeLabel: 'raw', price: 420 },
      { gradeLabel: 'PSA 10', price: 2800 },
      { gradeLabel: 'PSA 9', price: 850 },
      { gradeLabel: 'PSA 8', price: 520 },
      { gradeLabel: 'PSA 7', price: 440 },
      { gradeLabel: 'PSA 6', price: 430 },
      { gradeLabel: 'PSA 5', price: 425 },
      { gradeLabel: 'PSA 4', price: 422 },
      { gradeLabel: 'PSA 3', price: 421 },
      { gradeLabel: 'PSA 2', price: 420 },
      { gradeLabel: 'PSA 1', price: 420 },
      { gradeLabel: 'BGS 10', price: 4200 },
      { gradeLabel: 'BGS 9.5', price: 2600 },
      { gradeLabel: 'BGS 9', price: 800 },
      { gradeLabel: 'BGS 8.5', price: 500 },
      { gradeLabel: 'BGS 8', price: 460 },
      { gradeLabel: 'BGS 7.5', price: 445 },
      { gradeLabel: 'BGS 7', price: 435 },
      { gradeLabel: 'BGS 6.5', price: 430 },
      { gradeLabel: 'BGS 6', price: 428 },
      { gradeLabel: 'BGS 5.5', price: 426 },
      { gradeLabel: 'BGS 5', price: 424 },
      { gradeLabel: 'BGS 4.5', price: 423 },
      { gradeLabel: 'BGS 4', price: 422 },
      { gradeLabel: 'BGS 3.5', price: 421 },
      { gradeLabel: 'BGS 3', price: 421 },
      { gradeLabel: 'BGS 2.5', price: 420 },
      { gradeLabel: 'BGS 2', price: 420 },
      { gradeLabel: 'BGS 1.5', price: 420 },
      { gradeLabel: 'BGS 1', price: 420 },
      { gradeLabel: 'CGC 10', price: 2400 },
      { gradeLabel: 'CGC 9.5', price: 2200 },
      { gradeLabel: 'CGC 9', price: 750 },
      { gradeLabel: 'CGC 8.5', price: 480 },
      { gradeLabel: 'CGC 8', price: 450 },
      { gradeLabel: 'CGC 7.5', price: 440 },
      { gradeLabel: 'CGC 7', price: 435 },
      { gradeLabel: 'CGC 6.5', price: 430 },
      { gradeLabel: 'CGC 6', price: 428 },
      { gradeLabel: 'CGC 5.5', price: 426 },
      { gradeLabel: 'CGC 5', price: 424 },
      { gradeLabel: 'CGC 4.5', price: 423 },
      { gradeLabel: 'CGC 4', price: 422 },
      { gradeLabel: 'CGC 3.5', price: 421 },
      { gradeLabel: 'CGC 3', price: 421 },
      { gradeLabel: 'CGC 2.5', price: 420 },
      { gradeLabel: 'CGC 2', price: 420 },
      { gradeLabel: 'CGC 1.5', price: 420 },
      { gradeLabel: 'CGC 1', price: 420 },
      { gradeLabel: 'GRAAD 10', price: 2200 },
      { gradeLabel: 'GRAAD 9.5', price: 1800 },
      { gradeLabel: 'GRAAD 9', price: 700 },
      { gradeLabel: 'GRAAD 8.5', price: 460 },
      { gradeLabel: 'GRAAD 8', price: 440 },
      { gradeLabel: 'GRAAD 7.5', price: 435 },
      { gradeLabel: 'GRAAD 7', price: 430 },
      { gradeLabel: 'GRAAD 6.5', price: 428 },
      { gradeLabel: 'GRAAD 6', price: 426 },
      { gradeLabel: 'GRAAD 5.5', price: 424 },
      { gradeLabel: 'GRAAD 5', price: 422 },
      { gradeLabel: 'GRAAD 4.5', price: 421 },
      { gradeLabel: 'GRAAD 4', price: 421 },
      { gradeLabel: 'GRAAD 3.5', price: 420 },
      { gradeLabel: 'GRAAD 3', price: 420 },
      { gradeLabel: 'GRAAD 2.5', price: 420 },
      { gradeLabel: 'GRAAD 2', price: 420 },
      { gradeLabel: 'GRAAD 1.5', price: 420 },
      { gradeLabel: 'GRAAD 1', price: 420 },
    ]
  },

  {
    playerName: 'Lamine Yamal', setName: '2024-25 Panini Prizm FIFA',
    grades: [
      { gradeLabel: 'raw', price: 95 },
      { gradeLabel: 'PSA 10', price: 480 },
      { gradeLabel: 'PSA 9', price: 180 },
      { gradeLabel: 'PSA 8', price: 110 },
      { gradeLabel: 'PSA 7', price: 98 },
      { gradeLabel: 'PSA 6', price: 96 },
      { gradeLabel: 'PSA 5', price: 95 },
      { gradeLabel: 'PSA 4', price: 95 },
      { gradeLabel: 'PSA 3', price: 95 },
      { gradeLabel: 'PSA 2', price: 95 },
      { gradeLabel: 'PSA 1', price: 95 },
      { gradeLabel: 'BGS 10', price: 700 },
      { gradeLabel: 'BGS 9.5', price: 420 },
      { gradeLabel: 'BGS 9', price: 160 },
      { gradeLabel: 'BGS 8.5', price: 105 },
      { gradeLabel: 'BGS 8', price: 97 },
      { gradeLabel: 'BGS 7.5', price: 96 },
      { gradeLabel: 'BGS 7', price: 95 },
      { gradeLabel: 'BGS 6.5', price: 95 },
      { gradeLabel: 'BGS 6', price: 95 },
      { gradeLabel: 'BGS 5.5', price: 95 },
      { gradeLabel: 'BGS 5', price: 95 },
      { gradeLabel: 'BGS 4.5', price: 95 },
      { gradeLabel: 'BGS 4', price: 95 },
      { gradeLabel: 'BGS 3.5', price: 95 },
      { gradeLabel: 'BGS 3', price: 95 },
      { gradeLabel: 'BGS 2.5', price: 95 },
      { gradeLabel: 'BGS 2', price: 95 },
      { gradeLabel: 'BGS 1.5', price: 95 },
      { gradeLabel: 'BGS 1', price: 95 },
      { gradeLabel: 'CGC 10', price: 400 },
      { gradeLabel: 'CGC 9.5', price: 350 },
      { gradeLabel: 'CGC 9', price: 150 },
      { gradeLabel: 'CGC 8.5', price: 105 },
      { gradeLabel: 'CGC 8', price: 97 },
      { gradeLabel: 'CGC 7.5', price: 96 },
      { gradeLabel: 'CGC 7', price: 95 },
      { gradeLabel: 'CGC 6.5', price: 95 },
      { gradeLabel: 'CGC 6', price: 95 },
      { gradeLabel: 'CGC 5.5', price: 95 },
      { gradeLabel: 'CGC 5', price: 95 },
      { gradeLabel: 'CGC 4.5', price: 95 },
      { gradeLabel: 'CGC 4', price: 95 },
      { gradeLabel: 'CGC 3.5', price: 95 },
      { gradeLabel: 'CGC 3', price: 95 },
      { gradeLabel: 'CGC 2.5', price: 95 },
      { gradeLabel: 'CGC 2', price: 95 },
      { gradeLabel: 'CGC 1.5', price: 95 },
      { gradeLabel: 'CGC 1', price: 95 },
      { gradeLabel: 'GRAAD 10', price: 380 },
      { gradeLabel: 'GRAAD 9.5', price: 320 },
      { gradeLabel: 'GRAAD 9', price: 140 },
      { gradeLabel: 'GRAAD 8.5', price: 103 },
      { gradeLabel: 'GRAAD 8', price: 97 },
      { gradeLabel: 'GRAAD 7.5', price: 96 },
      { gradeLabel: 'GRAAD 7', price: 95 },
      { gradeLabel: 'GRAAD 6.5', price: 95 },
      { gradeLabel: 'GRAAD 6', price: 95 },
      { gradeLabel: 'GRAAD 5.5', price: 95 },
      { gradeLabel: 'GRAAD 5', price: 95 },
      { gradeLabel: 'GRAAD 4.5', price: 95 },
      { gradeLabel: 'GRAAD 4', price: 95 },
      { gradeLabel: 'GRAAD 3.5', price: 95 },
      { gradeLabel: 'GRAAD 3', price: 95 },
      { gradeLabel: 'GRAAD 2.5', price: 95 },
      { gradeLabel: 'GRAAD 2', price: 95 },
      { gradeLabel: 'GRAAD 1.5', price: 95 },
      { gradeLabel: 'GRAAD 1', price: 95 },
    ]
  },

  {
    playerName: 'Kylian Mbappé', setName: '2018-19 Panini Prizm FIFA',
    grades: [
      { gradeLabel: 'raw', price: 280 },
      { gradeLabel: 'PSA 10', price: 2200 },
      { gradeLabel: 'PSA 9', price: 650 },
      { gradeLabel: 'PSA 8', price: 320 },
      { gradeLabel: 'PSA 7', price: 290 },
      { gradeLabel: 'PSA 6', price: 285 },
      { gradeLabel: 'PSA 5', price: 282 },
      { gradeLabel: 'PSA 4', price: 281 },
      { gradeLabel: 'PSA 3', price: 280 },
      { gradeLabel: 'PSA 2', price: 280 },
      { gradeLabel: 'PSA 1', price: 280 },
      { gradeLabel: 'BGS 10', price: 3200 },
      { gradeLabel: 'BGS 9.5', price: 1900 },
      { gradeLabel: 'BGS 9', price: 580 },
      { gradeLabel: 'BGS 8.5', price: 310 },
      { gradeLabel: 'BGS 8', price: 293 },
      { gradeLabel: 'BGS 7.5', price: 288 },
      { gradeLabel: 'BGS 7', price: 285 },
      { gradeLabel: 'BGS 6.5', price: 283 },
      { gradeLabel: 'BGS 6', price: 282 },
      { gradeLabel: 'BGS 5.5', price: 281 },
      { gradeLabel: 'BGS 5', price: 281 },
      { gradeLabel: 'BGS 4.5', price: 280 },
      { gradeLabel: 'BGS 4', price: 280 },
      { gradeLabel: 'BGS 3.5', price: 280 },
      { gradeLabel: 'BGS 3', price: 280 },
      { gradeLabel: 'BGS 2.5', price: 280 },
      { gradeLabel: 'BGS 2', price: 280 },
      { gradeLabel: 'BGS 1.5', price: 280 },
      { gradeLabel: 'BGS 1', price: 280 },
      { gradeLabel: 'CGC 10', price: 1800 },
      { gradeLabel: 'CGC 9.5', price: 1600 },
      { gradeLabel: 'CGC 9', price: 520 },
      { gradeLabel: 'CGC 8.5', price: 305 },
      { gradeLabel: 'CGC 8', price: 290 },
      { gradeLabel: 'CGC 7.5', price: 287 },
      { gradeLabel: 'CGC 7', price: 284 },
      { gradeLabel: 'CGC 6.5', price: 283 },
      { gradeLabel: 'CGC 6', price: 282 },
      { gradeLabel: 'CGC 5.5', price: 281 },
      { gradeLabel: 'CGC 5', price: 281 },
      { gradeLabel: 'CGC 4.5', price: 280 },
      { gradeLabel: 'CGC 4', price: 280 },
      { gradeLabel: 'CGC 3.5', price: 280 },
      { gradeLabel: 'CGC 3', price: 280 },
      { gradeLabel: 'CGC 2.5', price: 280 },
      { gradeLabel: 'CGC 2', price: 280 },
      { gradeLabel: 'CGC 1.5', price: 280 },
      { gradeLabel: 'CGC 1', price: 280 },
      { gradeLabel: 'GRAAD 10', price: 1600 },
      { gradeLabel: 'GRAAD 9.5', price: 1400 },
      { gradeLabel: 'GRAAD 9', price: 480 },
      { gradeLabel: 'GRAAD 8.5', price: 300 },
      { gradeLabel: 'GRAAD 8', price: 288 },
      { gradeLabel: 'GRAAD 7.5', price: 285 },
      { gradeLabel: 'GRAAD 7', price: 283 },
      { gradeLabel: 'GRAAD 6.5', price: 282 },
      { gradeLabel: 'GRAAD 6', price: 281 },
      { gradeLabel: 'GRAAD 5.5', price: 281 },
      { gradeLabel: 'GRAAD 5', price: 280 },
      { gradeLabel: 'GRAAD 4.5', price: 280 },
      { gradeLabel: 'GRAAD 4', price: 280 },
      { gradeLabel: 'GRAAD 3.5', price: 280 },
      { gradeLabel: 'GRAAD 3', price: 280 },
      { gradeLabel: 'GRAAD 2.5', price: 280 },
      { gradeLabel: 'GRAAD 2', price: 280 },
      { gradeLabel: 'GRAAD 1.5', price: 280 },
      { gradeLabel: 'GRAAD 1', price: 280 },
    ]
  },

  // ══════════════════════════════════════
  // BASKET
  // ══════════════════════════════════════

  {
    playerName: 'Victor Wembanyama', setName: '2023-24 Panini Prizm NBA',
    grades: [
      { gradeLabel: 'raw', price: 95 },
      { gradeLabel: 'PSA 10', price: 580 },
      { gradeLabel: 'PSA 9', price: 200 },
      { gradeLabel: 'PSA 8', price: 115 },
      { gradeLabel: 'PSA 7', price: 98 },
      { gradeLabel: 'PSA 6', price: 96 },
      { gradeLabel: 'PSA 5', price: 95 },
      { gradeLabel: 'PSA 4', price: 95 },
      { gradeLabel: 'PSA 3', price: 95 },
      { gradeLabel: 'PSA 2', price: 95 },
      { gradeLabel: 'PSA 1', price: 95 },
      { gradeLabel: 'BGS 10', price: 850 },
      { gradeLabel: 'BGS 9.5', price: 520 },
      { gradeLabel: 'BGS 9', price: 180 },
      { gradeLabel: 'BGS 8.5', price: 110 },
      { gradeLabel: 'BGS 8', price: 97 },
      { gradeLabel: 'BGS 7.5', price: 96 },
      { gradeLabel: 'BGS 7', price: 95 },
      { gradeLabel: 'BGS 6.5', price: 95 },
      { gradeLabel: 'BGS 6', price: 95 },
      { gradeLabel: 'BGS 5.5', price: 95 },
      { gradeLabel: 'BGS 5', price: 95 },
      { gradeLabel: 'BGS 4.5', price: 95 },
      { gradeLabel: 'BGS 4', price: 95 },
      { gradeLabel: 'BGS 3.5', price: 95 },
      { gradeLabel: 'BGS 3', price: 95 },
      { gradeLabel: 'BGS 2.5', price: 95 },
      { gradeLabel: 'BGS 2', price: 95 },
      { gradeLabel: 'BGS 1.5', price: 95 },
      { gradeLabel: 'BGS 1', price: 95 },
      { gradeLabel: 'CGC 10', price: 500 },
      { gradeLabel: 'CGC 9.5', price: 440 },
      { gradeLabel: 'CGC 9', price: 170 },
      { gradeLabel: 'CGC 8.5', price: 108 },
      { gradeLabel: 'CGC 8', price: 97 },
      { gradeLabel: 'CGC 7.5', price: 96 },
      { gradeLabel: 'CGC 7', price: 95 },
      { gradeLabel: 'CGC 6.5', price: 95 },
      { gradeLabel: 'CGC 6', price: 95 },
      { gradeLabel: 'CGC 5.5', price: 95 },
      { gradeLabel: 'CGC 5', price: 95 },
      { gradeLabel: 'CGC 4.5', price: 95 },
      { gradeLabel: 'CGC 4', price: 95 },
      { gradeLabel: 'CGC 3.5', price: 95 },
      { gradeLabel: 'CGC 3', price: 95 },
      { gradeLabel: 'CGC 2.5', price: 95 },
      { gradeLabel: 'CGC 2', price: 95 },
      { gradeLabel: 'CGC 1.5', price: 95 },
      { gradeLabel: 'CGC 1', price: 95 },
      { gradeLabel: 'GRAAD 10', price: 460 },
      { gradeLabel: 'GRAAD 9.5', price: 400 },
      { gradeLabel: 'GRAAD 9', price: 160 },
      { gradeLabel: 'GRAAD 8.5', price: 106 },
      { gradeLabel: 'GRAAD 8', price: 97 },
      { gradeLabel: 'GRAAD 7.5', price: 96 },
      { gradeLabel: 'GRAAD 7', price: 95 },
      { gradeLabel: 'GRAAD 6.5', price: 95 },
      { gradeLabel: 'GRAAD 6', price: 95 },
      { gradeLabel: 'GRAAD 5.5', price: 95 },
      { gradeLabel: 'GRAAD 5', price: 95 },
      { gradeLabel: 'GRAAD 4.5', price: 95 },
      { gradeLabel: 'GRAAD 4', price: 95 },
      { gradeLabel: 'GRAAD 3.5', price: 95 },
      { gradeLabel: 'GRAAD 3', price: 95 },
      { gradeLabel: 'GRAAD 2.5', price: 95 },
      { gradeLabel: 'GRAAD 2', price: 95 },
      { gradeLabel: 'GRAAD 1.5', price: 95 },
      { gradeLabel: 'GRAAD 1', price: 95 },
    ]
  },

  {
    playerName: 'Luka Dončić', setName: '2018-19 Panini Prizm NBA',
    grades: [
      { gradeLabel: 'raw', price: 750 },
      { gradeLabel: 'PSA 10', price: 5500 },
      { gradeLabel: 'PSA 9', price: 1800 },
      { gradeLabel: 'PSA 8', price: 900 },
      { gradeLabel: 'PSA 7', price: 780 },
      { gradeLabel: 'PSA 6', price: 760 },
      { gradeLabel: 'PSA 5', price: 755 },
      { gradeLabel: 'PSA 4', price: 752 },
      { gradeLabel: 'PSA 3', price: 751 },
      { gradeLabel: 'PSA 2', price: 750 },
      { gradeLabel: 'PSA 1', price: 750 },
      { gradeLabel: 'BGS 10', price: 8000 },
      { gradeLabel: 'BGS 9.5', price: 4800 },
      { gradeLabel: 'BGS 9', price: 1600 },
      { gradeLabel: 'BGS 8.5', price: 860 },
      { gradeLabel: 'BGS 8', price: 770 },
      { gradeLabel: 'BGS 7.5', price: 762 },
      { gradeLabel: 'BGS 7', price: 757 },
      { gradeLabel: 'BGS 6.5', price: 754 },
      { gradeLabel: 'BGS 6', price: 753 },
      { gradeLabel: 'BGS 5.5', price: 752 },
      { gradeLabel: 'BGS 5', price: 751 },
      { gradeLabel: 'BGS 4.5', price: 751 },
      { gradeLabel: 'BGS 4', price: 750 },
      { gradeLabel: 'BGS 3.5', price: 750 },
      { gradeLabel: 'BGS 3', price: 750 },
      { gradeLabel: 'BGS 2.5', price: 750 },
      { gradeLabel: 'BGS 2', price: 750 },
      { gradeLabel: 'BGS 1.5', price: 750 },
      { gradeLabel: 'BGS 1', price: 750 },
      { gradeLabel: 'CGC 10', price: 4200 },
      { gradeLabel: 'CGC 9.5', price: 3800 },
      { gradeLabel: 'CGC 9', price: 1400 },
      { gradeLabel: 'CGC 8.5', price: 840 },
      { gradeLabel: 'CGC 8', price: 765 },
      { gradeLabel: 'CGC 7.5', price: 758 },
      { gradeLabel: 'CGC 7', price: 755 },
      { gradeLabel: 'CGC 6.5', price: 753 },
      { gradeLabel: 'CGC 6', price: 752 },
      { gradeLabel: 'CGC 5.5', price: 751 },
      { gradeLabel: 'CGC 5', price: 751 },
      { gradeLabel: 'CGC 4.5', price: 750 },
      { gradeLabel: 'CGC 4', price: 750 },
      { gradeLabel: 'CGC 3.5', price: 750 },
      { gradeLabel: 'CGC 3', price: 750 },
      { gradeLabel: 'CGC 2.5', price: 750 },
      { gradeLabel: 'CGC 2', price: 750 },
      { gradeLabel: 'CGC 1.5', price: 750 },
      { gradeLabel: 'CGC 1', price: 750 },
      { gradeLabel: 'GRAAD 10', price: 3800 },
      { gradeLabel: 'GRAAD 9.5', price: 3200 },
      { gradeLabel: 'GRAAD 9', price: 1200 },
      { gradeLabel: 'GRAAD 8.5', price: 820 },
      { gradeLabel: 'GRAAD 8', price: 762 },
      { gradeLabel: 'GRAAD 7.5', price: 756 },
      { gradeLabel: 'GRAAD 7', price: 753 },
      { gradeLabel: 'GRAAD 6.5', price: 752 },
      { gradeLabel: 'GRAAD 6', price: 751 },
      { gradeLabel: 'GRAAD 5.5', price: 751 },
      { gradeLabel: 'GRAAD 5', price: 750 },
      { gradeLabel: 'GRAAD 4.5', price: 750 },
      { gradeLabel: 'GRAAD 4', price: 750 },
      { gradeLabel: 'GRAAD 3.5', price: 750 },
      { gradeLabel: 'GRAAD 3', price: 750 },
      { gradeLabel: 'GRAAD 2.5', price: 750 },
      { gradeLabel: 'GRAAD 2', price: 750 },
      { gradeLabel: 'GRAAD 1.5', price: 750 },
      { gradeLabel: 'GRAAD 1', price: 750 },
    ]
  },

  // ══════════════════════════════════════
  // F1
  // ══════════════════════════════════════

  {
    playerName: 'Max Verstappen', setName: '2023 Topps Chrome F1',
    grades: [
      { gradeLabel: 'raw', price: 72 },
      { gradeLabel: 'PSA 10', price: 380 },
      { gradeLabel: 'PSA 9', price: 140 },
      { gradeLabel: 'PSA 8', price: 85 },
      { gradeLabel: 'PSA 7', price: 75 },
      { gradeLabel: 'PSA 6', price: 73 },
      { gradeLabel: 'PSA 5', price: 72 },
      { gradeLabel: 'PSA 4', price: 72 },
      { gradeLabel: 'PSA 3', price: 72 },
      { gradeLabel: 'PSA 2', price: 72 },
      { gradeLabel: 'PSA 1', price: 72 },
      { gradeLabel: 'BGS 10', price: 560 },
      { gradeLabel: 'BGS 9.5', price: 320 },
      { gradeLabel: 'BGS 9', price: 120 },
      { gradeLabel: 'BGS 8.5', price: 82 },
      { gradeLabel: 'BGS 8', price: 74 },
      { gradeLabel: 'BGS 7.5', price: 73 },
      { gradeLabel: 'BGS 7', price: 72 },
      { gradeLabel: 'BGS 6.5', price: 72 },
      { gradeLabel: 'BGS 6', price: 72 },
      { gradeLabel: 'BGS 5.5', price: 72 },
      { gradeLabel: 'BGS 5', price: 72 },
      { gradeLabel: 'BGS 4.5', price: 72 },
      { gradeLabel: 'BGS 4', price: 72 },
      { gradeLabel: 'BGS 3.5', price: 72 },
      { gradeLabel: 'BGS 3', price: 72 },
      { gradeLabel: 'BGS 2.5', price: 72 },
      { gradeLabel: 'BGS 2', price: 72 },
      { gradeLabel: 'BGS 1.5', price: 72 },
      { gradeLabel: 'BGS 1', price: 72 },
      { gradeLabel: 'CGC 10', price: 300 },
      { gradeLabel: 'CGC 9.5', price: 260 },
      { gradeLabel: 'CGC 9', price: 110 },
      { gradeLabel: 'CGC 8.5', price: 80 },
      { gradeLabel: 'CGC 8', price: 74 },
      { gradeLabel: 'CGC 7.5', price: 73 },
      { gradeLabel: 'CGC 7', price: 72 },
      { gradeLabel: 'CGC 6.5', price: 72 },
      { gradeLabel: 'CGC 6', price: 72 },
      { gradeLabel: 'CGC 5.5', price: 72 },
      { gradeLabel: 'CGC 5', price: 72 },
      { gradeLabel: 'CGC 4.5', price: 72 },
      { gradeLabel: 'CGC 4', price: 72 },
      { gradeLabel: 'CGC 3.5', price: 72 },
      { gradeLabel: 'CGC 3', price: 72 },
      { gradeLabel: 'CGC 2.5', price: 72 },
      { gradeLabel: 'CGC 2', price: 72 },
      { gradeLabel: 'CGC 1.5', price: 72 },
      { gradeLabel: 'CGC 1', price: 72 },
      { gradeLabel: 'GRAAD 10', price: 280 },
      { gradeLabel: 'GRAAD 9.5', price: 240 },
      { gradeLabel: 'GRAAD 9', price: 100 },
      { gradeLabel: 'GRAAD 8.5', price: 78 },
      { gradeLabel: 'GRAAD 8', price: 74 },
      { gradeLabel: 'GRAAD 7.5', price: 73 },
      { gradeLabel: 'GRAAD 7', price: 72 },
      { gradeLabel: 'GRAAD 6.5', price: 72 },
      { gradeLabel: 'GRAAD 6', price: 72 },
      { gradeLabel: 'GRAAD 5.5', price: 72 },
      { gradeLabel: 'GRAAD 5', price: 72 },
      { gradeLabel: 'GRAAD 4.5', price: 72 },
      { gradeLabel: 'GRAAD 4', price: 72 },
      { gradeLabel: 'GRAAD 3.5', price: 72 },
      { gradeLabel: 'GRAAD 3', price: 72 },
      { gradeLabel: 'GRAAD 2.5', price: 72 },
      { gradeLabel: 'GRAAD 2', price: 72 },
      { gradeLabel: 'GRAAD 1.5', price: 72 },
      { gradeLabel: 'GRAAD 1', price: 72 },
    ]
  },

  {
    playerName: 'Lando Norris', setName: '2023 Topps Chrome F1',
    grades: [
      { gradeLabel: 'raw', price: 55 },
      { gradeLabel: 'PSA 10', price: 280 },
      { gradeLabel: 'PSA 9', price: 110 },
      { gradeLabel: 'PSA 8', price: 65 },
      { gradeLabel: 'PSA 7', price: 57 },
      { gradeLabel: 'PSA 6', price: 56 },
      { gradeLabel: 'PSA 5', price: 55 },
      { gradeLabel: 'PSA 4', price: 55 },
      { gradeLabel: 'PSA 3', price: 55 },
      { gradeLabel: 'PSA 2', price: 55 },
      { gradeLabel: 'PSA 1', price: 55 },
      { gradeLabel: 'BGS 10', price: 420 },
      { gradeLabel: 'BGS 9.5', price: 240 },
      { gradeLabel: 'BGS 9', price: 95 },
      { gradeLabel: 'BGS 8.5', price: 62 },
      { gradeLabel: 'BGS 8', price: 57 },
      { gradeLabel: 'BGS 7.5', price: 56 },
      { gradeLabel: 'BGS 7', price: 55 },
      { gradeLabel: 'BGS 6.5', price: 55 },
      { gradeLabel: 'BGS 6', price: 55 },
      { gradeLabel: 'BGS 5.5', price: 55 },
      { gradeLabel: 'BGS 5', price: 55 },
      { gradeLabel: 'BGS 4.5', price: 55 },
      { gradeLabel: 'BGS 4', price: 55 },
      { gradeLabel: 'BGS 3.5', price: 55 },
      { gradeLabel: 'BGS 3', price: 55 },
      { gradeLabel: 'BGS 2.5', price: 55 },
      { gradeLabel: 'BGS 2', price: 55 },
      { gradeLabel: 'BGS 1.5', price: 55 },
      { gradeLabel: 'BGS 1', price: 55 },
      { gradeLabel: 'CGC 10', price: 220 },
      { gradeLabel: 'CGC 9.5', price: 190 },
      { gradeLabel: 'CGC 9', price: 85 },
      { gradeLabel: 'CGC 8.5', price: 60 },
      { gradeLabel: 'CGC 8', price: 57 },
      { gradeLabel: 'CGC 7.5', price: 56 },
      { gradeLabel: 'CGC 7', price: 55 },
      { gradeLabel: 'CGC 6.5', price: 55 },
      { gradeLabel: 'CGC 6', price: 55 },
      { gradeLabel: 'CGC 5.5', price: 55 },
      { gradeLabel: 'CGC 5', price: 55 },
      { gradeLabel: 'CGC 4.5', price: 55 },
      { gradeLabel: 'CGC 4', price: 55 },
      { gradeLabel: 'CGC 3.5', price: 55 },
      { gradeLabel: 'CGC 3', price: 55 },
      { gradeLabel: 'CGC 2.5', price: 55 },
      { gradeLabel: 'CGC 2', price: 55 },
      { gradeLabel: 'CGC 1.5', price: 55 },
      { gradeLabel: 'CGC 1', price: 55 },
      { gradeLabel: 'GRAAD 10', price: 200 },
      { gradeLabel: 'GRAAD 9.5', price: 170 },
      { gradeLabel: 'GRAAD 9', price: 75 },
      { gradeLabel: 'GRAAD 8.5', price: 58 },
      { gradeLabel: 'GRAAD 8', price: 56 },
      { gradeLabel: 'GRAAD 7.5', price: 55 },
      { gradeLabel: 'GRAAD 7', price: 55 },
      { gradeLabel: 'GRAAD 6.5', price: 55 },
      { gradeLabel: 'GRAAD 6', price: 55 },
      { gradeLabel: 'GRAAD 5.5', price: 55 },
      { gradeLabel: 'GRAAD 5', price: 55 },
      { gradeLabel: 'GRAAD 4.5', price: 55 },
      { gradeLabel: 'GRAAD 4', price: 55 },
      { gradeLabel: 'GRAAD 3.5', price: 55 },
      { gradeLabel: 'GRAAD 3', price: 55 },
      { gradeLabel: 'GRAAD 2.5', price: 55 },
      { gradeLabel: 'GRAAD 2', price: 55 },
      { gradeLabel: 'GRAAD 1.5', price: 55 },
      { gradeLabel: 'GRAAD 1', price: 55 },
    ]
  },
]

async function main() {
  console.log('🌱 Seed prezzi per grade...')
  let inserted = 0
  let skipped = 0

  for (const cp of cardPrices) {
    const card = await prisma.card.findFirst({
      where: { playerName: cp.playerName, setName: cp.setName },
    })

    if (!card) {
      console.log(`  ⚠️  Carta non trovata: ${cp.playerName} — ${cp.setName}`)
      continue
    }

    for (const g of cp.grades) {
      // Controlla se esiste già
      const existing = await prisma.priceHistory.findFirst({
        where: { cardId: card.id, gradeLabel: g.gradeLabel },
      })

      if (existing) {
        // Aggiorna il prezzo esistente
        await prisma.priceHistory.update({
          where: { id: existing.id },
          data: { price: new Prisma.Decimal(g.price) },
        })
        skipped++
      } else {
        await prisma.priceHistory.create({
          data: {
            cardId: card.id,
            gradeLabel: g.gradeLabel,
            price: new Prisma.Decimal(g.price),
            source: 'manual',
            platform: 'ebay',
            saleDate: new Date(),
          },
        })
        inserted++
      }
    }
    console.log(`  ✅ ${cp.playerName} — ${cp.setName} (${cp.grades.length} grade)`)
  }

  console.log(`\n✅ Completato: ${inserted} prezzi inseriti, ${skipped} aggiornati`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())